drop table if exists public.films,
 public.users,
 public.film_genre,
 public.film_mpa,
 public.film_likes,
 public.friends,
 public.genre,
 public.film_likes;


create table if not exists public.users (
	id integer generated by default as identity not null primary key,
	name varchar(100),
	email varchar(100)  not null,
	login varchar (50)  not null,
	birthday timestamp
);

create table if not exists public.film_mpa (
	id integer generated by default as identity not null primary key,
	name varchar(50)
);

CREATE TABLE public.genre (
	id integer generated by default as identity not null primary key,
	name varchar(50) NOT null
);


create table if not exists public.films (
	id integer generated by default as identity not null primary key,
	name varchar(100) ,
	description varchar(255),
	release_date timestamp,
	duration integer,
	mpa_id integer
);

create table if not exists public.film_genre (
	genre_id integer,
	film_id integer
);

create table if not exists public.film_likes (
	user_id integer,
	film_id integer
);

create table if not exists public.friends (
	user_id integer,
	friend_id integer
);

ALTER TABLE public.films ADD CONSTRAINT films_fk FOREIGN KEY (mpa_id) REFERENCES public.film_mpa(id) ON DELETE CASCADE ON UPDATE cascade;
ALTER TABLE public.film_likes  ADD CONSTRAINT film_likes_fk FOREIGN KEY (film_id) REFERENCES public.films(id) ON DELETE CASCADE ON UPDATE cascade;
ALTER TABLE public.film_likes  ADD CONSTRAINT film_likes_fk_1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE cascade;
ALTER TABLE public.friends ADD CONSTRAINT friends_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE cascade;
ALTER TABLE public.film_genre ADD CONSTRAINT film_genre_fk FOREIGN KEY (genre_id) REFERENCES public.genre(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public.film_genre ADD CONSTRAINT film_genre_fk_1 FOREIGN KEY (film_id) REFERENCES public.films(id) ON DELETE CASCADE ON UPDATE CASCADE;

